<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\slideshow
 * @category   CategoryName
 */

use open20\amos\core\forms\ActiveForm;
use open20\amos\core\forms\CloseSaveButtonWidget;
use open20\amos\core\forms\CreatedUpdatedWidget;
use open20\amos\core\forms\Tabs;
use open20\amos\slideshow\AmosSlideshow;

/**
 * @var yii\web\View $this
 * @var \open20\amos\slideshow\models\SlideshowRoute $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="slideshow-route-form col-xs-12 nop">
    
    <?php $form = ActiveForm::begin(); ?>
    
    <?php $this->beginBlock('generale'); ?>

    <div class="col-lg-6 col-sm-6">
        
        <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
        $form->field($model, 'slideshow_id')->dropDownList(
            \yii\helpers\ArrayHelper::map(\open20\amos\slideshow\models\Slideshow::find()->all(), 'id', 'name'),
            ['prompt' => AmosSlideshow::t('amosslideshow', 'Select')]
        ); ?>
    </div>

    <div class="col-lg-6 col-sm-6">
        
        <?= $form->field($model, 'route')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="clearfix"></div>
    <?php $this->endBlock(); ?>
    
    <?php $itemsTab[] = [
        'label' => AmosSlideshow::tHtml('amosslideshow', 'Generale '),
        'content' => $this->blocks['generale'],
    ];
    ?>
    
    <?= Tabs::widget([
        'encodeLabels' => false,
        'items' => $itemsTab
    ]); ?>
    <div class="col-xs-12 note_asterisk nop">
        <p>I campi <span class="red">*</span> sono obbligatori.</p>
    </div>
    <?= CreatedUpdatedWidget::widget(['model' => $model]) ?>
    <?= CloseSaveButtonWidget::widget(['model' => $model]); ?>
    <?php ActiveForm::end(); ?>
</div>
